# Generated by Django 5.1.5 on 2025-01-23 17:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payment_frequency',
            field=models.CharField(choices=[('H', 'Hourly'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
