# Generated by Django 5.1.5 on 2025-01-24 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_job_payment_frequency_job_salary_delete_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employment.address'),
        ),
        migrations.AlterField(
            model_name='job',
            name='added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
