# Generated by Django 5.1.5 on 2025-01-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0004_alter_employee_address_alter_job_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applied_jobs', to='employment.employee'),
        ),
    ]
