# Generated by Django 5.1.5 on 2025-01-26 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0004_alter_employee_address_alter_job_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.TextField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.job')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='applied_jobs',
            field=models.ManyToManyField(blank=True, related_name='applicants', through='employment.Application', to='employment.job'),
        ),
    ]
