# Generated by Django 5.1.5 on 2025-01-27 15:45

import django.core.validators
import employment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0006_application_unique_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(default='', upload_to='employment/resumes', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), employment.validators.validate_file_size]),
            preserve_default=False,
        ),
    ]
