# Generated by Django 5.1.5 on 2025-01-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0008_alter_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='expertise',
            field=models.CharField(default='Nothing', max_length=255),
            preserve_default=False,
        ),
    ]
