# Generated by Django 5.1.6 on 2025-03-02 20:49

import employment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_pics', validators=[employment.validators.validate_file_size]),
        ),
    ]
