# Generated by Django 5.1.6 on 2025-03-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0013_tag_job_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(related_name='jobs', to='employment.tag'),
        ),
    ]
