# Generated by Django 5.1.6 on 2025-03-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0014_alter_job_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='employment.tag'),
        ),
    ]
