# Generated by Django 5.1.6 on 2026-05-14 17:45

import employment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0015_alter_job_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expire',
            field=models.DateField(blank=True, null=True, validators=[employment.validators.validate_expire_date]),
        ),
    ]
